/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-31 04:00:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import donation.member.model.vo.Member;
import java.util.*;
import donation.member.model.vo.Member;

public final class managerMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/manager/managerHeader.jsp", Long.valueOf(1509413753179L));
    _jspx_dependants.put("/views/manager/managerFooter.jsp", Long.valueOf(1509413753179L));
    _jspx_dependants.put("/views/manager/../../header.jsp", Long.valueOf(1509413753976L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("donation.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 ArrayList<Member> list = (ArrayList<Member>) request.getAttribute("list"); 
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\t\r\n");
      out.write("\t<meta charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>Talent Donation - Manager/member</title>\r\n");
      out.write("\t<link href=\"/semi/css/manager/member.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("\t<link href=\"/semi/css/manager/mainFonts.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("    <script src=\"/semi/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t$(function (){\r\n");
      out.write("    \t\t$('.main-menu ul #home').removeClass('active');\r\n");
      out.write("    \t\t$('.main-menu ul #category').removeClass('active');\r\n");
      out.write("    \t\t$('.main-menu ul #board').removeClass('active');\r\n");
      out.write("    \t\t$('.main-menu ul #minfo').addClass('active');\r\n");
      out.write("    \t    \r\n");
      out.write("    \t    $(\".memberList tr\").click(function(){\r\n");
      out.write("    \t        $.ajax({\r\n");
      out.write("    \t\t\t\turl: \"/semi/mgrmemberdetail\",\r\n");
      out.write("    \t\t\t\tdata: {memberId: $(this).children().first().text()},\r\n");
      out.write("    \t\t\t\ttype: \"get\",\r\n");
      out.write("    \t\t\t\tdataType: \"json\",\r\n");
      out.write("    \t\t\t\tsuccess: function(data){\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberId]\").val(data.memberId);\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberNic]\").val(decodeURIComponent(data.memberNik));\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberName]\").val(decodeURIComponent(data.memberName));\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberPhone]\").val(data.memberPhone);\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberEmail]\").val(data.memberEmail);\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=memberAddress]\").val(decodeURIComponent(data.memberAddress));\r\n");
      out.write("    \t\t\t\t\t$(\"input[name=talent]\").val(decodeURIComponent(data.talent));\r\n");
      out.write("    \t\t\t\t\tif(data.mgrChat == 'Y') {\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrChat]:input[value=\"N\"]').attr(\"checked\", false);\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrChat]:input[value=\"Y\"]').attr(\"checked\", true);\r\n");
      out.write("    \t\t\t\t\t} else {\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrChat]:input[value=\"Y\"]').attr(\"checked\", false);\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrChat]:input[value=\"N\"]').attr(\"checked\", true);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\tif(data.mgrLogin == 'Y') {\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrlogin]:input[value=\"N\"]').attr(\"checked\", false);\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrlogin]:input[value=\"Y\"]').attr(\"checked\", true);\r\n");
      out.write("    \t\t\t\t\t} else {\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrlogin]:input[value=\"Y\"]').attr(\"checked\", false);\r\n");
      out.write("    \t\t\t\t\t\t$('input:radio[name=mgrlogin]:input[value=\"N\"]').attr(\"checked\", true);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\terror: function(data){\r\n");
      out.write("    \t\t\t\t\tconsole.log(\"에러 발생 : \" + data);\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("    \t    });  \t    \r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction suggest() {\r\n");
      out.write("    \t\tlocation.href = \"/semi/swrite?reciver=\"+$(\"input[name='memberId']\").val()+\"&sender=\"+\"admin\";\t\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div#loginbar{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tmargin-right:50px;\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("\tfont-size:10pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=loginbar>\r\n");
 if(member ==null){ 
      out.write("\r\n");
      out.write("\t<a href=\"/semi/views/member/Login.jsp\">로그인</a>\r\n");
      out.write("\t<a href=\"/semi/views/member/Insert.jsp\" style=\"margin-left:10px;\">회원가입</a>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/semi/minfor?userid=");
      out.print(member.getMemberId());
      out.write('"');
      out.write('>');
      out.print(member.getMemberNik() );
      out.write("</a>님 환영합니다.\r\n");
      out.write("\t<a href=\"/semi/logout?userid=");
      out.print(member.getMemberId() );
      out.write("\" style=\"margin-left:10px;\">로그아웃</a>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>Talent Donation - Manager</title>\t\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/font-awesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/templatemo_misc.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/templatemo_style.css\">\r\n");
      out.write("    <script src=\"/semi/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div id=\"menu-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"logo-wrapper col-md-4 col-sm-2\">\r\n");
      out.write("\t\t\t\t\t<a style=\"text-shadow:1px 1px 1px gray;\">다재다능</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-10 main-menu text-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"toggle-menu visible-sm visible-xs\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"menu-first\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"home\"><a href=\"/semi/mgrmain\">Home_관리자</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"minfo\"><a href=\"/semi/mgrmember\">회원정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"category\"><a href=\"/semi/clist\">카테고리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"board\"><a href=\"/semi/nlist\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"container1 col-md-4 col-sm-12 col-md-offset-2\">\r\n");
      out.write("\t\t\t<form id=\"search-body\">\r\n");
      out.write("\t\t\t\t<button id=\"s-btn-body\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t<span id=\"s-btn\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div id=\"s-form-body\">\r\n");
      out.write("\t\t\t\t\t<input id=\"s-form\" type=\"text\" placeholder=\"Search Keyword\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"memberList\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"cols\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"cols\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"cols\">재능</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
for(Member m : list) {
						if(!m.getMemberId().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(m.getMemberId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(m.getMemberName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(m.getTalent());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} if(list.size()<13) { 
							for(int i=list.size(); i<=13; i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr><td></td><td></td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-4 col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t\t\t<h2\tstyle=\"border-bottom: 0px; text-shadow:1px 1px 2px gray;\">회원 상세정보</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form class=\"memberDetail\" action=\"/semi/mgrmupdate\">\r\n");
      out.write("\t\t\t\t<table class=\"memberDetail\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input name=\"memberId\" value=\"\" readonly class=\"form-control\" id=\"input-text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"memberName\" value=\"\" readonly class=\"form-control\" id=\"input-text\"></td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th>닉네임</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"memberNic\" value=\"\" readonly class=\"form-control\"\tid=\"input-text\" placeholder=\"\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"number\" name=\"memberPhone\" value=\"\" readonly class=\"form-control\" id=\"input-text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"email\" name=\"memberEmail\" value=\"\" readonly class=\"form-control\"\tid=\"input-text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input name=\"memberAddress\" value=\"\" readonly class=\"form-control\" id=\"input-text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>재능</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input id=\"talent\" name=\"talent\" value=\"\" readonly class=\"form-control\"\tid=\"input-text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>접속가능</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\" id=\"mgrController\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"mgrlogin\" value=\"Y\"> ON\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"mgrlogin\" value=\"N\"> OFF\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th>채팅가능</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\" id=\"mgrController\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"mgrChat\" value=\"Y\"> ON\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"mgrChat\" value=\"N\"> OFF\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table><br>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" onclick=\"return suggest();\" class=\"btn btn-success\" style=\"margin-right:10px;\">쪽지보내기</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">수정</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>Talent Donation - Manager</title>\t\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/font-awesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/templatemo_misc.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/semi/css/templatemo_style.css\">\r\n");
      out.write("    <script src=\"/semi/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br style=\"clear:left;\"><br>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-xs-12 text-left\">\r\n");
      out.write("\t\t\t\t\t<span>Copyright &copy; 2017 다재다능 (Talent Donation)</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 hidden-xs text-right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#top\" id=\"go-top\">Back to top</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
