/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2017-10-31 11:21:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import donation.member.model.vo.Member;
import java.util.ArrayList;
import java.sql.Date;

public final class Insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("donation.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

      ArrayList<Member> list = (ArrayList<Member>)request.getAttribute("list");
   
   int flag1 = 0;
   int flag2 = 0;
   
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert member</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/css/loginstyle2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <h1 align=\"center\"\r\n");
      out.write("      style=\"margin-top: 50px; font-size: 60pt; color: white;\">\r\n");
      out.write("      <a href=\"../../index.jsp\" style=\"color: white; text-decoration: none;\">다재다능</a>\r\n");
      out.write("   </h1>\r\n");
      out.write("   <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"login-page\">\r\n");
      out.write("      <div class=\"form\">\r\n");
      out.write("\r\n");
      out.write("         <form class=\"login-form\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" id=\"memberid\" placeholder=\"아이디\" name=\"memberid\" />\r\n");
      out.write("            <button onclick=\"butn_confirm1();return false;\">중복확인</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" id=\"membername\" placeholder=\"이름\"\r\n");
      out.write("               name=\"membername\" /> <input type=\"text\" placeholder=\"주민번호(-제외)\"\r\n");
      out.write("               name=\"memberno\" /> <input type=\"password\" id=\"pwd1\"\r\n");
      out.write("               placeholder=\"비밀번호\" name=\"memberpwd1\" /> <input type=\"password\"\r\n");
      out.write("               id=\"pwd2\" placeholder=\"비밀번호 확인\" name=\"memberpwd2\" />\r\n");
      out.write("            <button onclick=\"checkpwd();return false;\">중복확인</button>\r\n");
      out.write("            <input type=\"text\" placeholder=\"닉네임\" name=\"membernik\" id=\"membernik\" />\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"주소\" name=\"memberaddress1\" /> <input\r\n");
      out.write("               type=\"text\" placeholder=\"상세주소\" name=\"memberaddress2\" /> <input\r\n");
      out.write("               type=\"text\" placeholder=\"이메일\" name=\"memberemail\" /> <input\r\n");
      out.write("               type=\"text\" placeholder=\"전화번호\" name=\"memberphone\" />\r\n");
      out.write("\r\n");
      out.write("            <table>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기1\"\r\n");
      out.write("                     style=\"width: 30px;\">IT</td>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기2\"\r\n");
      out.write("                     style=\"width: 30px;\">디자인</td>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기3\"\r\n");
      out.write("                     style=\"width: 30px;\">마케팅</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기4\"\r\n");
      out.write("                     style=\"width: 30px;\">음악</td>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기5\"\r\n");
      out.write("                     style=\"width: 30px;\">노하우/상담</td>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기6\"\r\n");
      out.write("                     style=\"width: 30px;\">번역</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기7\"\r\n");
      out.write("                     style=\"width: 30px;\">건강</td>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"talent\" value=\"특기8\"\r\n");
      out.write("                     style=\"width: 30px;\">기타</td>\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <button onclick=\"insert()\">create</button>\r\n");
      out.write("\r\n");
      out.write("         </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function butn_confirm1(){\r\n");
      out.write("      var id = document.getElementById('memberid').value;\r\n");
      out.write("      var idtext = document.getElementById('memberid');\r\n");
      out.write("      var flag = 0; \r\n");
      out.write("      \r\n");
      out.write("      ");
for(int i=0;i<list.size();i++){  
      out.write("\r\n");
      out.write("            if(id == '");
      out.print(list.get(i).getMemberId());
      out.write("')\r\n");
      out.write("               flag =1;\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      if(id.length < 8){\r\n");
      out.write("         alert(\"8자리 이상해주세요.\");\r\n");
      out.write("         idtext.value=\"\";\r\n");
      out.write("      }else if(flag == 1){\r\n");
      out.write("         \r\n");
      out.write("         alert(\"아이디가 중복입니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      else{\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("         alert(\"확인되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function checkpwd(){\r\n");
      out.write("      var pwd1 = document.getElementById('pwd1').value;\r\n");
      out.write("      var pwd2 = document.getElementById('pwd2').value;\r\n");
      out.write("      \r\n");
      out.write("      if(pwd1 == pwd2){\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         alert(\"확인되었습니다.\");\r\n");
      out.write("      }else{\r\n");
      out.write("         alert(\"비밀번호가 같지 않습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function insert(){\r\n");
      out.write("      \r\n");
      out.write("           var id = document.getElementById('memberid').value;\r\n");
      out.write("         var idtext = document.getElementById('memberid');\r\n");
      out.write("         var flag = 0; \r\n");
      out.write("         \r\n");
      out.write("         if(id.length < 8){\r\n");
      out.write("           flag = 0;\r\n");
      out.write("         }\r\n");
      out.write("         else{\r\n");
      out.write("            flag = 1;\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         ");
for(int i=0;i<list.size();i++){  
      out.write("\r\n");
      out.write("          if(id == '");
      out.print(list.get(i).getMemberId());
      out.write("')\r\n");
      out.write("             flag =0;\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        var pwd1 = document.getElementById('pwd1').value;\r\n");
      out.write("         var pwd2 = document.getElementById('pwd2').value;\r\n");
      out.write("         var flag2 = 0;\r\n");
      out.write("         \r\n");
      out.write("         if(pwd1 == pwd2){\r\n");
      out.write("            flag2 = 1;\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("         }else{\r\n");
      out.write("            flag2 = 0;\r\n");
      out.write("          \r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      alert( flag );\r\n");
      out.write("       alert( flag2 );\r\n");
      out.write("      \r\n");
      out.write("      if(flag == 1 && flag2 == 1)\r\n");
      out.write("      {\r\n");
      out.write("         flag1 = 0;\r\n");
      out.write("         flag2 = 0;\r\n");
      out.write("         \r\n");
      out.write("         //서블릿으로 이동하는거 보내시면 됩니다.\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </script>\r\n");
      out.write("   <script src=\"/semi/js/loginjs.js\"></script>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
