/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-11-01 19:23:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import donation.member.model.vo.Member;
import java.util.ArrayList;
import java.sql.Date;

public final class Insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("donation.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

      ArrayList<Member> list = (ArrayList<Member>)request.getAttribute("list");
   
   int flag1 = 0;
   int flag2 = 0;
   
   boolean insertR = true;
   
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert member</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/css/loginstyle2.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/semi/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction insert(){\r\n");
      out.write("\t   var result = true;\r\n");
      out.write("\t   ");
insertR=true;
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t   var memberId = $('input[name=\"memberid\"]').val();\r\n");
      out.write("\t   var memberName = $('input[name=\"membername\"]').val();\r\n");
      out.write("\t   var memberNo = $('input[name=\"memberno\"]').val();\r\n");
      out.write("\t   var memberPwd = $('input[name=\"memberpwd1\"]').val();\r\n");
      out.write("\t   var memberPwdCk = $('input[name=\"memberpwd2\"]').val();\r\n");
      out.write("\t   var memberNik = $('input[name=\"membernik\"]').val();\r\n");
      out.write("\t   var memberAddress = $('input[name=\"memberaddress1\"]').val();\r\n");
      out.write("\t   var memberAddressDetail = $('input[name=\"memberaddress2\"]').val();\r\n");
      out.write("\t   var memberEmail = $('input[name=\"memberemail\"]').val();\r\n");
      out.write("\t   var memberPhone = $('input[name=\"memberphone\"]').val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   //alert(memberId+\"\\n\"+memberName+\"\\n\"+memberNo+\"\\n\"+memberPwd+\"\\n\"+memberPwdCk+\"\\n\"+memberNik+\"\\n\"+memberAddress+\"\\n\"+memberAddressDetail+\"\\n\"+memberEmail+\"\\n\"+memberPhone);\r\n");
      out.write("\t   \r\n");
      out.write("\t   var allData = {\"memberId\":memberId, \"memberNo\":memberNo, \"memberPwd\":memberPwd, \"memberNik\":memberNik, \"memberPhone\":memberPhone};\r\n");
      out.write("\t\t$.ajax({url:\"/semi/menrollcheck\",\r\n");
      out.write("\t\t\t\tdata:allData,\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data!=\"success\") {\r\n");
      out.write("\t\t\t\t\t\t\tif(data==\"글자수초과\") {alert(\"아이디 또는 비밀번호 최대 글자 수를 조과하였습니다.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"영문자와숫자만\") {alert(\"아이디와 비밀번호는 영문자와 숫자만 입력가능합니다.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"영문자와숫자모두\") {alert(\"아이디와 비밀번호는 영문자와 숫자의 조합으로 입력하세요.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"ID중복\") {alert(\"ID가 중복되었습니다.\\n다른 ID를 입력해주세요.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"주민확인\") {alert(\"주민등록번호를 확인하세요.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"닉네임중복\") {alert(\"닉네임이 중복되었습니다.\\n다른 닉네임을 입력해주세요.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t\telse if(data==\"번호확인\") {alert(\"전화번호를 확인해주세요.\"); ");
insertR = false;
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t} else {");
insertR=true;
      out.write("}\r\n");
      out.write("\t\t\t\t },\r\n");
      out.write("\t\t\t\t error:function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"에러 발생 : \"+data);\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\tresult = ");
      out.print(insertR);
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t   if(memberId==\"\" || memberName==\"\" || memberNo==\"\" || memberPwd==\"\" || memberPwdCk==\"\"\r\n");
      out.write("\t\t || memberNik==\"\" || memberAddress==\"\" || memberAddressDetail==\"\" \r\n");
      out.write("\t\t || memberEmail==\"\" || memberPhone==\"\"){ alert(\"모든 항목을 입력하세요.\"); result=false; }\r\n");
      out.write("\t   \r\n");
      out.write("\t   else if(memberPwd!=memberPwdCk) { alert(\"비밀번호를 확인하세요.\"); result=false;}\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   return result;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1 align=\"center\"\r\n");
      out.write("\t\tstyle=\"margin-top: 50px; font-size: 60pt; color: white;\">\r\n");
      out.write("\t\t<a href=\"/semi/index.jsp\" style=\"color: white; text-decoration: none;\">다재다능</a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"login-page\">\r\n");
      out.write("\t\t<div class=\"form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form class=\"login-form\" action=\"/semi/minsert\" method=\"post\" id=\"login-form\" name=\"login-form\" onSubmit=\"return insert();\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"memberid\" placeholder=\"아이디\" name=\"memberid\" value=\"wltjs1796\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"membername\" placeholder=\"이름\"\r\n");
      out.write("\t\t\t\t\tname=\"membername\" value=\"윤지선\"/> <input type=\"text\" placeholder=\"주민번호(-제외)\"\r\n");
      out.write("\t\t\t\t\tname=\"memberno\" id=\"memberno\" value=\"9510102200614\"/> <input type=\"password\" id=\"pwd1\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"비밀번호\" name=\"memberpwd1\" /> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tid=\"pwd2\" placeholder=\"비밀번호 확인\" name=\"memberpwd2\" />\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"닉네임\" name=\"membernik\" id=\"membernik\" value=\"지선짱짱\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"주소\" name=\"memberaddress1\"\r\n");
      out.write("\t\t\t\t\tid=\"memberaddress1\" value=\"경기도 안산시 단원구\"/> <input type=\"text\" placeholder=\"상세주소\"\r\n");
      out.write("\t\t\t\t\tname=\"memberaddress2\" id=\"memberaddress2\" value=\"222-2번지\"/> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"이메일\" name=\"memberemail\" id=\"memberemail\" value=\"wltjs1796@naver.com\"/> <input\r\n");
      out.write("\t\t\t\t\ttype=\"text\" placeholder=\"전화번호\" name=\"memberphone\" id=\"memberphone\" value=\"01062436597\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기1\" style=\"width: 30px;\">IT</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기2\" style=\"width: 30px;\">디자인</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기3\" style=\"width: 30px;\">마케팅</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기4\" style=\"width: 30px;\">음악</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기5\" style=\"width: 30px;\">노하우/상담</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기6\" style=\"width: 30px;\">번역</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기7\" style=\"width: 30px;\">건강</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"talent\" class=\"talent\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"특기8\" style=\"width: 30px;\">기타</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<!-- <button onclick=\"return insert();\">create</button> -->\r\n");
      out.write("\t\t\t\t<button type=\"submit\">create</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("   function butn_confirm1(event){\r\n");
      out.write("\t   \r\n");
      out.write("      var id = document.getElementById('memberid').value;\r\n");
      out.write("      var idtext = document.getElementById('memberid');\r\n");
      out.write("      var flag = 0; \r\n");
      out.write("      \r\n");
      out.write("      ");
for(int i=0;i<list.size();i++){  
      out.write("\r\n");
      out.write("            if(id == '");
      out.print(list.get(i).getMemberId());
      out.write("')\r\n");
      out.write("               flag =1;\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      if(id.length < 8){\r\n");
      out.write("         alert(\"8자리 이상해주세요.\");\r\n");
      out.write("         idtext.value=\"\";\r\n");
      out.write("      }else if(flag == 1){\r\n");
      out.write("         \r\n");
      out.write("         alert(\"아이디가 중복입니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      else{\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("         alert(\"확인되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function checkpwd(){\r\n");
      out.write("      alert(\"확인\");\r\n");
      out.write("\t  var pwd1 = document.getElementById('pwd1').value;\r\n");
      out.write("      var pwd2 = document.getElementById('pwd2').value;\r\n");
      out.write("      if(id.length < 8){\r\n");
      out.write("          alert(\"8자리 이상해주세요.\");\r\n");
      out.write("          idtext.value=\"\";\r\n");
      out.write("          else if(pwd1 == pwd2){\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         alert(\"확인되었습니다.\");\r\n");
      out.write("      }else{\r\n");
      out.write("         alert(\"비밀번호가 같지 않습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("          \r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("\t<script src=\"/semi/js/loginjs.js\"></script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
